---
title: "ChickensAnalysis"
author: "Sawsan Alamoodi"
date:  "4/5/2020"
output: html_document 

---

```{r setup, include=FALSE} 
 knitr::opts_chunk$set(echo = FALSE ,message = FALSE ,warning = FALSE)


library(tidyverse)
library(rio)
library(Hmisc)
library(shiny)
library(agricolae)
library(DT) 
```



**Descriptive Statistics**
```{r chickavg}
t<- chickwts %>% 
  group_by(feed) %>% 
  summarise(n=length(feed),avg = mean(weight), SD=sd(weight)) 
datatable(t)

```
 **Plots**

```{r chickbox , echo=FALSE}

ggplot(chickwts, aes(x = feed, y = weight)) +
  geom_boxplot()
```


```{r chickjit , echo=FALSE}

ggplot(chickwts, aes(x = feed, y = weight)) +
  geom_jitter(width = 0.30) +
  stat_summary(fun.data = mean_sdl, 
               fun.args = list(mult = 1), 
               col = "red") 
```



**Inferential Statistics**

The one-way ANOVA summary:
```{r chicklm , echo=FALSE}

chickwts_lm <- lm(weight ~ feed, data = chickwts)
chickwts_lm

datatable(anova(chickwts_lm))
```

Tukey’s Post-hoc test:
```{r chickAv , echo=FALSE}

chickwts.av <-aov(weight ~ feed , data = chickwts)
tukeyTest <- TukeyHSD(chickwts.av)
datatable(tukeyTest$feed)
```